## End-to-end test phase marker.
##
## Emits a single UART line of the form `@e2e <phase>:<kind> [k=v]...` plus
## (when JTAG memory log is configured) a fixed-size record into the ring
## buffer. Used by the soak harness to bucket attempts by failure phase.
##
## The Phase and Kind enums are GENERATED by tools/gen_e2e_marker_nim.py.
## Edit tools/e2e_phases.py and re-run `python tools/gen_e2e_marker_nim.py`.

import ../uart

## --- BEGIN GENERATED PHASE/KIND ENUM (do not edit by hand) ---
type
  Phase* = enum
    attempt = "attempt"
    scan = "scan"
    auth = "auth"
    ph4whs = "4whs"
    assoc = "assoc"
    dhcp = "dhcp"
    tcp = "tcp"
    adv_start = "adv_start"
    connect_req = "connect_req"
    mtu = "mtu"
    gatt_read = "gatt_read"
    disconnect = "disconnect"

  Kind* = enum
    start = "start"
    ok = "ok"
    fail = "fail"
    info = "info"
## --- END GENERATED PHASE/KIND ENUM ---

# Caller supplies the console UART. We keep it as a module-global pointer set
# once at startup so phaseMark() doesn't take the UART as an argument and stays
# usable from anywhere.
var markerConsole: ptr Uart

proc e2eMarkerInit*(console: ptr Uart) =
  markerConsole = console

template kvWrite*(key: string, value: untyped): untyped =
  ## Helper for phaseMark callers: emits ` key=value` if marker UART is up.
  if markerConsole != nil:
    discard markerConsole[].sendByte(' '.uint8)
    discard markerConsole[].sendString(key)
    discard markerConsole[].sendByte('='.uint8)
    when value is string:
      discard markerConsole[].sendString(value)
    elif value is SomeUnsignedInt:
      markerConsole[].sendHex32(value.uint32)
    elif value is SomeSignedInt:
      markerConsole[].sendHex32(cast[uint32](value.int32))
    else:
      discard markerConsole[].sendString($value)

template phaseMark*(phase: Phase, kind: Kind, kv: untyped = (discard)): untyped =
  ## Emit one structured marker line. `kv` is a stmt block of `kvWrite(...)` calls.
  if markerConsole != nil:
    discard markerConsole[].sendString("@e2e ")
    discard markerConsole[].sendString($phase)
    discard markerConsole[].sendByte(':'.uint8)
    discard markerConsole[].sendString($kind)
    block: kv
    discard markerConsole[].sendLine("")
