## End-to-end SRAM-PUF key derivation test (M0).
##
## Closes the loop the raw-capture test left open: on every cold boot, the
## device reads the real SRAM PUF window, runs the fuzzy extractor (majority-vote
## repetition decode via public helper data) + HKDF to derive the 32-byte vault
## root, and prints SHA-256(root). If that hash is identical across cold power
## cycles, the *extracted key* — not just the raw SRAM input — is reproducible on
## hardware.
##
## Built with the PUF linker (-d:bl808puf) so OCRAM stays pristine. Helper data
## is generated by tools/puf/puf_enroll.py from a reference capture.

import bl808/startup, bl808/core
import bl808/mmio, bl808/memmap
import bl808/glb, bl808/gpio, bl808/uart
import bl808/puf/helper, bl808/puf/reconstruct
import bl808/enclave/sha256
import bl808/panicoverride
import bl808/kernel/alloc
include puf_helper_data

const
  ConsoleBaud {.intdefine.} = 230_400'u32
  ConsoleClkHz {.intdefine.} = 40_000_000'u32
  PufWindow = OcramBase + 0x2000'u   # 0x22022000, the enrolled window

var console: Uart

proc main() {.exportc, cdecl.} =
  systemInit()
  heapInit()
  enablePeriphClock(periphUart0)
  setMcuXclkSource(mcuXclkXtal)
  setUartClock(true, uartClkXclk, 0)
  gpioSetupUart(14, 15)
  console = initUart(uart0, UartConfig(
    baudRate: ConsoleBaud, dataBits: data8, stopBits: stop1, parity: parityNone), ConsoleClkHz)

  # Build the helper from the enrolled, embedded data.
  var hlp: PufHelper
  hlp.r = PufHelperR
  for i in 0 ..< PufHelperIdx.len:
    hlp.indices[i] = PufHelperIdx[i]
    hlp.offset[i] = PufHelperOff[i]

  # Reconstruct the device root from real SRAM, then hash it (one-way, so the
  # printed value reveals nothing about the key but lets us compare boots).
  var root: array[32, uint8]
  reconstructRoot(PufWindow, hlp, root)
  let rootHash = sha256(root)

  discard console.sendLine("")
  discard console.sendLine("=== BL808 PUF Root Derivation Test ===")

  proc emit() =
    discard console.sendString("[PUF] rootsha=")
    for i in 0 ..< 8:
      console.sendHex32(
        rootHash[i*4].uint32 or (rootHash[i*4+1].uint32 shl 8) or
        (rootHash[i*4+2].uint32 shl 16) or (rootHash[i*4+3].uint32 shl 24))
      discard console.sendString(" ")
    discard console.sendLine("")
    discard console.sendLine("=== Root Complete ===")

  # Re-emit so the host catches it after the USB-serial re-enumerates post-boot.
  while true:
    emit()
    for _ in 0 ..< 30_000_000:
      {.emit: "__asm__ volatile(\"nop\");".}
