## Secure-boot verify test (device-side NSB1 verification on real PKA hardware).
##
## Embeds a host-signed NSB1 image + the signer's public key (sb_test_vector.nim,
## generated by tools/secureboot). On silicon it:
##   1. verifies the genuine image (ECDSA-P256 via PKA) -> expect vrOk,
##   2. flips a payload byte                          -> expect vrBadHash,
##   3. flips a signature byte                        -> expect vrBadSignature.

import bl808/startup, bl808/core
import bl808/mmio, bl808/memmap
import bl808/glb, bl808/gpio, bl808/uart
import bl808/secureboot/container, bl808/secureboot/verify
import bl808/panicoverride
import bl808/kernel/alloc
include sb_test_vector

const
  ConsoleUartTxPin = 14'u32
  ConsoleUartRxPin = 15'u32
  ConsoleBaud {.intdefine.} = 230_400'u32
  ConsoleClkHz {.intdefine.} = 40_000_000'u32

var
  console: Uart
  passed = 0
  failed = 0

proc check(label: string, ok: bool) =
  discard console.sendString(if ok: "[PASS] " else: "[FAIL] ")
  discard console.sendLine(label)
  if ok: inc passed else: inc failed

proc main() {.exportc, cdecl.} =
  systemInit()
  heapInit()
  enableAllPeriphClocks()
  enablePeriphClock(periphUart0)
  setMcuXclkSource(mcuXclkXtal)
  setUartClock(true, uartClkXclk, 0)
  gpioSetupUart(ConsoleUartTxPin, ConsoleUartRxPin)
  console = initUart(uart0, UartConfig(
    baudRate: ConsoleBaud, dataBits: data8, stopBits: stop1, parity: parityNone), ConsoleClkHz)

  discard console.sendLine("")
  discard console.sendLine("=== BL808 Secure Boot Verify Test ===")

  var img: array[SbImageLen, uint8]
  for i in 0 ..< SbImageLen: img[i] = SbImage[i]
  var hdr: Nsb1Header

  # 1. genuine image verifies
  check("genuine NSB1 image verifies (ECDSA via PKA)",
        verifyNsb1(img, SbPubX, SbPubY, hdr) == vrOk)

  # 2. tampered payload -> hash mismatch
  img[Nsb1HeaderSize + 8] = img[Nsb1HeaderSize + 8] xor 0xFF
  check("tampered payload rejected (bad hash)",
        verifyNsb1(img, SbPubX, SbPubY, hdr) == vrBadHash)
  img[Nsb1HeaderSize + 8] = img[Nsb1HeaderSize + 8] xor 0xFF   # restore

  # 3. tampered signature -> signature failure
  img[OffSignature + 4] = img[OffSignature + 4] xor 0xFF
  check("tampered signature rejected",
        verifyNsb1(img, SbPubX, SbPubY, hdr) == vrBadSignature)

  discard console.sendString("Result: ")
  console.sendHex32(passed.uint32)
  discard console.sendString(" passed, ")
  console.sendHex32(failed.uint32)
  discard console.sendLine(" failed")
  if failed == 0:
    discard console.sendLine("=== Test Complete ===")
  else:
    discard console.sendLine("=== Test Failed ===")
  while true:
    wfi()
