## Host-visible firmware configuration selector IDs.

const
  API_AC_BK* = 0'u8
  API_AC_BE* = 1'u8
  API_AC_VI* = 2'u8
  API_AC_VO* = 3'u8
  API_AC_MAX* = 4'u8

  TASK_MM_CFG_KEEP_ALIVE_STATUS_ENABLED*     = 0
  TASK_MM_CFG_KEEP_ALIVE_TIME_LAST_RECEIVED* = 1
  TASK_MM_CFG_KEEP_ALIVE_PACKET_COUNTER*     = 2
  TASK_MM_CFG_ACCEPT_ALL_BEACON_FOR_STA*     = 3
  TASK_MM_CFG_ACCEPT_ALL_BEACON_FOR_AP*      = 4
  TASK_MM_CFG_BEACON_TIMEOUT*                = 5
  TASK_MM_CFG_PSM_TBTT_PRE*                  = 6
  TASK_MM_CFG_PS_TX_TIMEOUT*                 = 7

  TASK_SM_CFG_AUTH_ASSOC_RETRY_LIMIT*        = 0
  TASK_SM_CFG_RECONNECT_TRIGGER_FLAG*        = 1
  TASK_SM_CFG_AUTH_START_DELAY*              = 2

  TASK_SCAN_CFG_DURATION_SCAN_PASSIVE*       = 0
  TASK_SCAN_CFG_DURATION_SCAN_ACTIVE*        = 1
  TASK_SCAN_CFG_DURATION_SCAN_JOIN_ACTIVE*   = 2
