{.passC: "-Isrc/bl808".}
when defined(bl808WifiRealLwip):
  {.passC: "-Isrc/bl808/kernel/lwip_wifi_smoke".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/wifi_manager/bl60x_wifi_driver/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/wifi_manager/bl60x_wifi_driver".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/wifi/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/wifi_hosal/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/lwip/src/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/lwip/lwip-port".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/lwip/lwip-port/arch".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/lwip/lwip-port/config".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/lwip/lwip-port/FreeRTOS".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/os/freertos_e907/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/os/freertos_e907/portable/GCC/RISC-V".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/platform/hosal/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/platform/hosal/bl808_e907_hal".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/platform/soc/bl808/bl808_e907_std/bl808_bsp_driver/std_drv/inc".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/platform/soc/bl808/bl808_e907_std/bl808_bsp_driver/regs".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/platform/soc/bl808/bl808_e907_std/bl808_bsp_driver/risc-v/Core/Include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/os/bl_os_adapter/bl_os_adapter/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/os/bl_os_adapter/bl_os_adapter/include/bl_os_adapter".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/stage/yloop/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/wpa_supplicant/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/wpa_supplicant/include/bl_supplicant".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/wpa_supplicant/include/utils".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/wpa_supplicant/port/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/wpa_supplicant/src".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/wpa_supplicant/src/crypto".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/blcrypto_suite/inc".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/blcrypto_suite/priv_inc".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/security/mbedtls_lts/mbedtls/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/utils/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/dns_server/include".}
{.passC: "-Ibuild/bl_iot_sdk_b773b3f/components/network/netutils/include".}
