#!/usr/bin/env python3
"""Compare the Nim BLE controller object against the vendor BLE controller.

This is intentionally a parity/audit tool, not a proof of functional BLE RF
behavior. It answers three concrete questions:

* Are all globally defined vendor text symbols present in the Nim build?
* Which common functions are materially shorter in Nim than in the blob?
* Which vendor symbols are still generated by the placeholder stub template?
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


def run(args: list[str]) -> str:
    return subprocess.check_output(args, text=True, errors="ignore")


def nm_functions(path: Path) -> set[str]:
    text = run(["riscv64-unknown-elf-nm", "-g", "--defined-only", str(path)])
    out: set[str] = set()
    for line in text.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-2] in {"T", "t"}:
            out.add(parts[-1])
    return out


def parse_objdump(path: Path) -> dict[str, dict[str, list[str]]]:
    text = run(["riscv64-unknown-elf-objdump", "-d", str(path)])
    current: str | None = None
    out: dict[str, dict[str, list[str]]] = {}
    for line in text.splitlines():
        header = re.match(r"^\s*([0-9a-fA-F]+) <([^>]+)>:$", line)
        if header:
            current = header.group(2)
            out.setdefault(current, {"bytes": [], "mnem": []})
            continue
        if current is None:
            continue
        insn = re.match(r"^\s*[0-9a-fA-F]+:\s*([0-9a-fA-F]+)\s+([.A-Za-z0-9_]+)", line)
        if insn:
            out[current]["bytes"].append(insn.group(1).lower())
            out[current]["mnem"].append(insn.group(2))
    return out


def source_lines(source: Path) -> tuple[dict[str, int], set[str], dict[str, int]]:
    lines: dict[str, int] = {}
    stubs: set[str] = set()
    stub_lines: dict[str, int] = {}
    if not source.exists():
        return lines, stubs, stub_lines
    for line_no, line in enumerate(source.read_text(errors="ignore").splitlines(), start=1):
        proc_match = re.match(r"\s*proc\s+([A-Za-z_][A-Za-z0-9_]*)\*?", line)
        if proc_match:
            lines.setdefault(proc_match.group(1), line_no)
        stub_match = re.match(r"\s*vendorZeroStub\(([^)]+)\)", line)
        if stub_match:
            symbol = stub_match.group(1).strip()
            stubs.add(symbol)
            stub_lines.setdefault(symbol, line_no)
            lines.setdefault(symbol, line_no)
    return lines, stubs, stub_lines


def likely_active_placeholder_stub(
    symbol: str,
    nim_instr: int,
    line_map: dict[str, int],
    stub_lines: dict[str, int],
) -> bool:
    return (
        nim_instr <= 2
        and symbol in stub_lines
        and line_map.get(symbol) == stub_lines.get(symbol)
    )


def severity_buckets(items: list[dict[str, object]]) -> dict[str, int]:
    buckets = {">=200": 0, "100-199": 0, "50-99": 0, "25-49": 0, "10-24": 0, "1-9": 0}
    for item in items:
        missing = int(item["missing_instr"])
        if missing >= 200:
            buckets[">=200"] += 1
        elif missing >= 100:
            buckets["100-199"] += 1
        elif missing >= 50:
            buckets["50-99"] += 1
        elif missing >= 25:
            buckets["25-49"] += 1
        elif missing >= 10:
            buckets["10-24"] += 1
        elif missing >= 1:
            buckets["1-9"] += 1
    return buckets


def function_instruction_count(
    disassembly: dict[str, dict[str, list[str]]],
    symbol: str,
) -> int:
    """Count a symbol plus GCC local body fragments such as foo.part.0."""
    total = len(disassembly.get(symbol, {}).get("bytes", []))
    prefix = f"{symbol}."
    for name, body in disassembly.items():
        if name.startswith(prefix):
            suffix = name[len(prefix):]
            if (
                suffix.startswith("part.")
                or suffix.startswith("isra.")
                or suffix.startswith("constprop.")
            ):
                total += len(body["bytes"])
    return total


def build_report(ref: Path, nim: Path, source: Path) -> dict[str, object]:
    ref_funcs = nm_functions(ref)
    nim_funcs = nm_functions(nim)
    common = sorted(ref_funcs & nim_funcs)
    ref_dis = parse_objdump(ref)
    nim_dis = parse_objdump(nim)
    line_map, stub_symbols, stub_lines = source_lines(source)

    checked: list[str] = []
    byte_identical: list[str] = []
    mnemonic_identical: list[str] = []
    smaller: list[dict[str, object]] = []

    for symbol in common:
        if symbol not in ref_dis or symbol not in nim_dis:
            continue
        checked.append(symbol)
        ref_instr = function_instruction_count(ref_dis, symbol)
        nim_instr = function_instruction_count(nim_dis, symbol)
        if ref_dis[symbol]["bytes"] == nim_dis[symbol]["bytes"]:
            byte_identical.append(symbol)
        if ref_dis[symbol]["mnem"] == nim_dis[symbol]["mnem"]:
            mnemonic_identical.append(symbol)
        if nim_instr < ref_instr:
            source_stub = symbol in stub_symbols
            likely_active_stub = likely_active_placeholder_stub(
                symbol,
                nim_instr,
                line_map,
                stub_lines,
            )
            smaller.append(
                {
                    "symbol": symbol,
                    "ref_instr": ref_instr,
                    "nim_instr": nim_instr,
                    "missing_instr": ref_instr - nim_instr,
                    "pct_of_ref": round((nim_instr / ref_instr) * 100, 2) if ref_instr else 0,
                    "line": line_map.get(symbol),
                    "placeholder_stub": source_stub,
                    "likely_active_placeholder_stub": likely_active_stub,
                }
            )

    smaller.sort(key=lambda item: (int(item["missing_instr"]), str(item["symbol"])), reverse=True)
    stub_rows: list[dict[str, object]] = []
    active_stub_count = 0
    for symbol in sorted(stub_symbols & ref_funcs):
        nim_instr = function_instruction_count(nim_dis, symbol)
        likely_active = likely_active_placeholder_stub(
            symbol,
            nim_instr,
            line_map,
            stub_lines,
        )
        if likely_active:
            active_stub_count += 1
        stub_rows.append(
            {
                "symbol": symbol,
                "ref_instr": function_instruction_count(ref_dis, symbol),
                "nim_instr": nim_instr,
                "line": line_map.get(symbol),
                "likely_active": likely_active,
            }
        )
    stub_rows.sort(key=lambda item: (int(item["ref_instr"]), str(item["symbol"])), reverse=True)

    return {
        "reference": str(ref),
        "nim_binary": str(nim),
        "source": str(source),
        "reference_functions": len(ref_funcs),
        "nim_functions": len(nim_funcs),
        "common_functions": len(ref_funcs & nim_funcs),
        "missing_in_nim": sorted(ref_funcs - nim_funcs),
        "extra_in_nim": sorted(nim_funcs - ref_funcs),
        "functions_with_disassembly": len(checked),
        "byte_identical_functions": len(byte_identical),
        "mnemonic_identical_functions": len(mnemonic_identical),
        "nim_smaller_count": len(smaller),
        "severity_buckets": severity_buckets(smaller),
        "smaller_methods": smaller,
        "placeholder_stub_count": len(stub_symbols),
        "placeholder_stubs_in_reference_count": len(stub_rows),
        "likely_active_placeholder_stubs_in_reference_count": active_stub_count,
        "placeholder_stubs_in_reference": stub_rows,
    }


def write_markdown(report: dict[str, object], path: Path) -> None:
    missing = report["missing_in_nim"]
    smaller = report["smaller_methods"]
    stubs = report["placeholder_stubs_in_reference"]
    buckets = report["severity_buckets"]
    assert isinstance(missing, list)
    assert isinstance(smaller, list)
    assert isinstance(stubs, list)
    assert isinstance(buckets, dict)

    lines = [
        "# BLE Controller Under-Implemented Methods",
        "",
        f"- Reference: `{report['reference']}`",
        f"- Nim object/archive: `{report['nim_binary']}`",
        f"- Source: `{report['source']}`",
        f"- Reference functions: **{report['reference_functions']}**",
        f"- Nim functions: **{report['nim_functions']}**",
        f"- Common functions: **{report['common_functions']}**",
        f"- Missing reference functions in Nim: **{len(missing)}**",
        f"- Method count where Nim is smaller than blob: **{report['nim_smaller_count']}**",
        f"- Placeholder stubs in source: **{report['placeholder_stub_count']}**",
        f"- Placeholder stubs matching reference symbols: **{report['placeholder_stubs_in_reference_count']}**",
        f"- Likely active placeholder stubs in this build: **{report['likely_active_placeholder_stubs_in_reference_count']}**",
        "- Severity buckets: "
        + ", ".join(f"{key}: {buckets[key]}" for key in [">=200", "100-199", "50-99", "25-49", "10-24", "1-9"]),
        "- Note: instruction deltas are local to each symbol body; wrappers that delegate to helper functions can still appear short.",
        "",
    ]

    if missing:
        lines += ["## Missing Reference Symbols", ""]
        lines += [f"- `{symbol}`" for symbol in missing]
        lines += [""]

    lines += [
        "## Largest Shorter Methods",
        "",
        "| # | Symbol | src line | ref | nim | missing | nim/ref % | source stub | active stub |",
        "|---:|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for idx, item in enumerate(smaller[:80], start=1):
        assert isinstance(item, dict)
        line = item.get("line")
        lines.append(
            f"| {idx} | `{item['symbol']}` | {line if line is not None else ''} | "
            f"{item['ref_instr']} | {item['nim_instr']} | {item['missing_instr']} | "
            f"{item['pct_of_ref']} | {'yes' if item['placeholder_stub'] else 'no'} | "
            f"{'yes' if item['likely_active_placeholder_stub'] else 'no'} |"
        )

    lines += [
        "",
        "## Largest Placeholder Stubs",
        "",
        "| # | Symbol | src line | ref instr | nim instr | active |",
        "|---:|---|---:|---:|---:|---|",
    ]
    for idx, item in enumerate(stubs[:80], start=1):
        assert isinstance(item, dict)
        line = item.get("line")
        lines.append(
            f"| {idx} | `{item['symbol']}` | {line if line is not None else ''} | "
            f"{item['ref_instr']} | {item['nim_instr']} | "
            f"{'yes' if item['likely_active'] else 'no'} |"
        )

    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("reference", type=Path)
    parser.add_argument("nim_binary", type=Path)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("src/bl808/blecontroller.nim"),
        help="Nim source used for line/stub annotations",
    )
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--markdown-out", type=Path)
    parser.add_argument("--fail-on-missing", action="store_true")
    args = parser.parse_args()

    for label, path in [("reference", args.reference), ("nim binary", args.nim_binary)]:
        if not path.exists():
            print(f"{label} not found: {path}", file=sys.stderr)
            return 2

    report = build_report(args.reference, args.nim_binary, args.source)
    if args.json_out is not None:
        args.json_out.write_text(json.dumps(report, indent=2) + "\n")
    if args.markdown_out is not None:
        write_markdown(report, args.markdown_out)

    print(f"Reference funcs: {report['reference_functions']}")
    print(f"Nim funcs:       {report['nim_functions']}")
    print(f"Common funcs:    {report['common_functions']}")
    print(f"Missing in Nim:  {len(report['missing_in_nim'])}")
    print(f"Extra in Nim:    {len(report['extra_in_nim'])}")
    print(f"Disassembled common funcs: {report['functions_with_disassembly']}")
    print(f"Byte-identical funcs:      {report['byte_identical_functions']}")
    print(f"Mnemonic-identical funcs:  {report['mnemonic_identical_functions']}")
    print(f"Nim-smaller funcs:         {report['nim_smaller_count']}")
    print(f"Placeholder stubs:         {report['placeholder_stub_count']}")
    print(f"Reference placeholder stubs: {report['placeholder_stubs_in_reference_count']}")
    print(
        "Likely active reference placeholder stubs: "
        f"{report['likely_active_placeholder_stubs_in_reference_count']}"
    )

    top = report["smaller_methods"]
    assert isinstance(top, list)
    if top:
        print("")
        print("Top shorter methods:")
        for item in top[:12]:
            assert isinstance(item, dict)
            print(
                f"  {item['symbol']}: {item['ref_instr']} vs {item['nim_instr']} "
                f"(delta {item['missing_instr']}, stub={item['placeholder_stub']})"
            )

    if args.fail_on_missing and report["missing_in_nim"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
